### PR TITLE
Publish both raw and flasher images as artifacts

### PR DESCRIPTION
**Pull request by mtoman**

### CODE REVIEW

**Comment by mtoman** [comment]
@resin-jenkins retest this please

**Comment by mtoman** [comment]
@resin-jenkins retest this please

**Comment by mtoman** [comment]
@resin-jenkins test this please

**Comment by kaisoz** [comment]
@resin-jenkins retest

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Comment by mtoman** [comment]
This is now working

**Pull request closed without merging**
