### PR TITLE
balena-yocto-scripts: Update to v1.21.3

### PR DESCRIPTION
**Pull request by alexgg**
Update balena-yocto-scripts from v1.19.30 to v1.21.3

Change-type: patch
Changelog-entry: Update balena-yocto-scripts to v1.21.3

### CODE REVIEW

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Review by floion — APPROVED** [review]

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
`test-genericx86-64` failure to flash:

```
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T15:42:51.225Z][302ff6a-hup] DUT powered off
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T15:42:51.226Z][302ff6a-hup] Preparing to flash, attempt 1...
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T15:57:41.112Z][302ff6a-hup] Preparing to flash, attempt 2...
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:12:45.044Z][302ff6a-hup] Preparing to flash, attempt 3...
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:27:27.910Z][302ff6a-hup] Preparing to flash, attempt 4...
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:42:43.676Z][302ff6a-hup] Preparing to flash, attempt 5...
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.776Z][302ff6a-hup]         not ok 1 - Timed out while trying to flash internal storage!!status: done
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]           ---
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]           stack: |
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]             Request.<anonymous> (lib/common/worker.js:167:16)
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]             IncomingMessage.<anonymous> (node_modules/request/request.js:1073:12)
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]           at:
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]             line: 167
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]             column: 16
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]             file: lib/common/worker.js
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]             function: Request.<anonymous>
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.777Z][302ff6a-hup]           test: Rollback tests
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.778Z][302ff6a-hup]           source: |
jenkins-leviathan-v2-template-42333-client-1  | [2024-03-02T16:57:13.778Z][302ff6a-hup]             								req.cancel();
jenkins-leviathan-v2-template-42333-client-1  |             								reject(new Error(computedLine[2]));
jenkins-leviathan-v2-template-42333-client-1  |             ---------------^
jenkins-leviathan-v2-template-42333-client-1  |             							}
jenkins-leviathan-v2-template-42333-client-1  |           ...
```

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
@resin-jenkins retest this please

**Comment by rcooke-warwick** [comment]
retesting now another test device is set up

**Comment by alexgg** [comment]
Depends on https://github.com/balena-os/balena-intel/pull/724

**Pull request merged**
