### PR TITLE
genericx86-64-ext: Extend the number of built-in drivers

### PR DESCRIPTION
**Pull request by alexgg**
This commit extends the number of built-in drivers to enhance the
flasher image so that it can install into a wider variety of devices.

Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@alexgg this PR is missing a `Changelog-entry`.

**Comment by alexgg** [comment]
> @alexgg this PR is missing a `Changelog-entry`.

Added now.

**Comment by alexgg** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@balena-ci retest

**Pull request merged**
