### PR TITLE
layers/meta-balena: Update to v2.83.4

### PR DESCRIPTION
**Pull request by alexgg**
Update meta-balena from 2.83.1 to 2.83.4

Changelog-entry: Update meta-balena from v2.83.1 to v2.83.4
Signed-off-by: Alex Gonzalez <alexg@balena.io>

### CODE REVIEW

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
Looks like a minor space issue:
```
ERROR: balena-image-1.0-r0 do_image_docker: The rootfs size 1060864(K) exceeds IMAGE_ROOTFS_MAXSIZE: 1024000(K)
ERROR: Logfile of failure stored in: /work/build/tmp/work/genericx86_64_ext-poky-linux/balena-image/1.0-r0/temp/log.do_image_docker.814664
NOTE: recipe balena-image-1.0-r0: task do_image_docker: Failed
ERROR: Task (/work/build/../layers/meta-balena/meta-balena-common/recipes-core/images/balena-image.bb:do_image_docker) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5083 tasks of which 3945 didn't need to be rerun and 1 failed.
```

This PR should fix it:
https://github.com/balena-os/meta-balena/pull/2273

**Comment by alexgg** [comment]
@jakogut could you also please make sure we have bigger rootfs partitions on the `generic-amd64` DT that will replace the `genericx86-64-ext`? It's supposed to be big enough to build as many modules and firmware as required.

**Comment by alexgg** [comment]
Still
```
ERROR: balena-image-1.0-r0 do_image_docker: The rootfs size 1056768(K) exceeds IMAGE_ROOTFS_MAXSIZE: 1024000(K)
```

**Comment by alexgg** [comment]
Superseded by https://github.com/balena-os/balena-intel/pull/399

**Pull request closed without merging**
