### PR TITLE
balena-yocto-scripts: Update to v1.17.10

### PR DESCRIPTION
**Pull request by ab77**
Update balena-yocto-scripts from v1.17.9 to v1.17.10

Change-type: patch
Changelog-entry: Update balena-yocto-scripts to v1.17.10
Signed-off-by: Anton Belodedenko <anton@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
Embedded changelogs don't work correctly if the commit body includes the `v` prefixes IIRC.

**Comment by ab77** [comment]
> Embedded changelogs don't work correctly if the commit body includes the `v` prefixes IIRC.

is the "fix" to drop the `v`s?

**Review by klutchell — APPROVED** [review]
lgtm

**Comment by ab77** [comment]
@resin-jenkins test this please

**Pull request merged**
