### PR TITLE
Remove unused wireless firmware for the surface pro 6

### PR DESCRIPTION
**Pull request by alexgg**

### CODE REVIEW

**Comment by alexgg** [comment]
```
-IMAGESIZE = 282648
+IMAGESIZE = 253412
```
packages removed:
```
-linux-firmware-iwlwifi-qu-b0-hr-b0 linux-firmware-iwlwifi-qu-b0-hr-b0 linux-firmware 20210511 7103
-linux-firmware-iwlwifi-8265 linux-firmware-iwlwifi-8265 linux-firmware 20210511 2380
-linux-firmware-iwlwifi-8000c linux-firmware-iwlwifi-8000c linux-firmware 20210511 2371
-linux-firmware-iwlwifi-9000 linux-firmware-iwlwifi-9000 linux-firmware 20210511 1479
-linux-firmware-iwlwifi-9260 linux-firmware-iwlwifi-9260 linux-firmware 20210511 1451
-linux-firmware-iwlwifi-7265 linux-firmware-iwlwifi-7265 linux-firmware 20210511 1153
-linux-firmware-iwlwifi-cc-a0 linux-firmware-iwlwifi-cc-a0 linux-firmware 20210511 1071
-linux-firmware-iwlwifi-7260 linux-firmware-iwlwifi-7260 linux-firmware 20210511 1025
-linux-firmware-iwlwifi-7265d linux-firmware-iwlwifi-7265d linux-firmware 20210511 1012
-linux-firmware-iwlwifi-3168 linux-firmware-iwlwifi-3168 linux-firmware 20210511 1012
-linux-firmware-ibt-19-0-4 linux-firmware-ibt-19-0-4 linux-firmware 20210511 766
-linux-firmware-bcm43143 linux-firmware-bcm43143 linux-firmware 20210511 764
-linux-firmware-pcie8897 linux-firmware-pcie8897 linux-firmware 20210511 707
-linux-firmware-iwlwifi-135-6 linux-firmware-iwlwifi-135-6 linux-firmware 20210511 685
-linux-firmware-iwlwifi-6000g2b-6 linux-firmware-iwlwifi-6000g2b-6 linux-firmware 20210511 664
-linux-firmware-iwlwifi-6000g2a-6 linux-firmware-iwlwifi-6000g2a-6 linux-firmware 20210511 661
-linux-firmware-ibt-18-16-1 linux-firmware-ibt-18-16-1 linux-firmware 20210511 659
-linux-firmware-bcm43455 linux-firmware-bcm43455 linux-firmware 20210511 637
-linux-firmware-ibt-11-5 linux-firmware-ibt-11-5 linux-firmware 20210511 574
-linux-firmware-ibt-12-16 linux-firmware-ibt-12-16 linux-firmware 20210511 570
-linux-firmware-iwlwifi-6050-5 linux-firmware-iwlwifi-6050-5 linux-firmware 20210511 459
-linux-firmware-iwlwifi-6000-4 linux-firmware-iwlwifi-6000-4 linux-firmware 20210511 444
-linux-firmware-ath9k linux-firmware-ath9k linux-firmware 20210511 430
-linux-firmware-rtl8723 linux-firmware-rtl8723 linux-firmware 20210511 350
-linux-firmware-rtl8192su linux-firmware-rtl8192su linux-firmware 20210511 119
-linux-firmware-ibt-hw-37-8 linux-firmware-ibt-hw-37-8 linux-firmware 20210511 115
-linux-firmware-ibt-hw-37-7 linux-firmware-ibt-hw-37-7 linux-firmware 20210511 95
-linux-firmware-rtl8821 linux-firmware-rtl8821 linux-firmware 20210511 75
-linux-firmware-rtl8192cu linux-firmware-rtl8192cu linux-firmware 20210511 63
-linux-firmware-ralink linux-firmware-ralink linux-firmware 20210511 50
-linux-firmware-rtl8723b-bt linux-firmware-rtl8723b-bt linux-firmware 20210511 44
-linux-firmware-rtl8188eu linux-firmware-rtl8188eu linux-firmware 20210511 14
-linux-firmware-ralink-nic linux-firmware-ralink-nic linux-firmware 20210511 5
-linux-firmware-broadcom-license linux-firmware-broadcom-license linux-firmware 20210511 4
-linux-firmware-rtl-license linux-firmware-rtl-license linux-firmware 20210511 2
-linux-firmware-ralink-license linux-firmware-ralink-license linux-firmware 20210511 2
-linux-firmware-iwlwifi-license linux-firmware-iwlwifi-license linux-firmware 20210511 2
-linux-firmware-ibt-license linux-firmware-ibt-license linux-firmware 20210511 2
-linux-firmware-atheros-license linux-firmware-atheros-license linux-firmware 20210511 2
```

**Review by floion — APPROVED** [review]

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@balena-ci rebase

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
Last test failed with:
```
leviathan-v2-template-client-1  | [2022-06-30T15:52:35.402Z][65a9b86-cloud] Unpinning device from release
leviathan-v2-template-client-1  | [2022-06-30T15:52:37.859Z][65a9b86-cloud] Waiting for device to be running latest release...
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.625Z][65a9b86-cloud] # Subtest: Managed BalenaOS release suite
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.626Z][65a9b86-cloud]     not ok 1 - Condition async () => {         let deviceServices =           await this.balena.models.device.getWithServiceDetails(uuid);         let running = false;         running = services.every((service) => {           return (             deviceServices.current_services[service][0].status === 'Running' &&             deviceServices.current_services[service][0].commit === commit           );         });         return running;       } timed out
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.627Z][65a9b86-cloud]       ---
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.627Z][65a9b86-cloud]       stack: |
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.627Z][65a9b86-cloud]         			} timed out
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.627Z][65a9b86-cloud]             _waitUntil (lib/common/utils.js:97:11)
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.627Z][65a9b86-cloud]             _waitUntil (lib/common/utils.js:112:11)
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.627Z][65a9b86-cloud]             Object.waitUntil (lib/common/utils.js:115:3)
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.628Z][65a9b86-cloud]             BalenaSDK.waitUntilServicesRunning (lib/components/balena/sdk.js:506:3)
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.628Z][65a9b86-cloud]             Proxy.run (/data/suite/suite.js:350:5)
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.628Z][65a9b86-cloud]       test: Managed BalenaOS release suite
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.628Z][65a9b86-cloud]       ...
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.637Z][65a9b86-cloud] 
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.638Z][65a9b86-cloud]     Bail out! Condition async () => {
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.646Z][65a9b86-cloud] Bail out! Condition async () => {
leviathan-v2-template-client-1  | [2022-06-30T16:18:16.646Z][65a9b86-cloud] Test suite completed. Tearing down now.
```
https://jenkins.product-os.io/job/leviathan-v2-template/2384/console

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Pull request merged**
